#!/usr/bin/env bash
# Install (or repair) the ShotDeck desktop launcher, then start ShotDeck.
#
#   cd /software/pipeline/ShotDeck && ./install_desktop_launcher.sh
#
# Everything it writes is rewritten from the content below on every run, so
# running it twice leaves the same three files with the same bytes and the same
# modes -- no duplicates, no .bak copies. Nothing outside $HOME is touched
# except launch_shotdeck.sh, which this script owns.
set -euo pipefail

# The directory this script lives in: /software/pipeline/ShotDeck on the farm.
APP_ROOT="$(cd "$(dirname "$0")" && pwd)"
PYTHON="$APP_ROOT/shotdeck_venv/bin/python"
MAIN="$APP_ROOT/main.py"
ICON="$APP_ROOT/media/5and8_logo.png"
LAUNCHER="$APP_ROOT/launch_shotdeck.sh"

MENU_DIR="$HOME/.local/share/applications"
MENU_ENTRY="$MENU_DIR/ShotDeck.desktop"

# xdg-user-dir knows the localised name; plain ~/Desktop is the fallback.
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || true)"
[ -d "${DESKTOP_DIR:-}" ] || DESKTOP_DIR="$HOME/Desktop"
DESKTOP_ENTRY="$DESKTOP_DIR/ShotDeck.desktop"

die() { echo "ShotDeck install: $*" >&2; exit 1; }

# -- 1. what must already be there -------------------------------------------
# Checked before anything is written, so a bad install leaves nothing behind.
[ -x "$PYTHON" ] || die "no usable interpreter at $PYTHON"
[ -f "$MAIN" ]   || die "no application at $MAIN"
[ -f "$ICON" ]   || die "no icon at $ICON"

# -- 2. the wrapper the icon runs --------------------------------------------
# Rewritten every run: this file is the copy that matters, and an edited or
# truncated one is repaired rather than worked around.
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Start ShotDeck from a desktop icon. Generated by install_desktop_launcher.sh
# -- edit that script, not this one.
#
# A double-click sources no login shell, so anything the app needs from the
# environment is set here or the app comes up broken with nowhere to say why.
set -euo pipefail

# ShotGrid credentials, root-owned, one file per workstation (DEPLOY-ROCKY9 §5).
set -a
[ -r /etc/sgdesk/sgdesk.env ] && . /etc/sgdesk/sgdesk.env
set +a

# PySide6 renders the tiles wrong under Rocky 9's wayland session.
export QT_QPA_PLATFORM="\${QT_QPA_PLATFORM:-xcb}"

# Flat imports: config, paths and ui are top-level modules in the app root.
cd "$APP_ROOT"
exec "$PYTHON" "$MAIN" "\$@"
EOF
chmod 0755 "$LAUNCHER"

# -- 3. the desktop entry, one copy on the desktop and one in the menu --------
install -d -m 0755 "$MENU_DIR" "$DESKTOP_DIR"

cat > "$MENU_ENTRY" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=ShotDeck
Comment=ShotDeck Pipeline
Exec=$LAUNCHER
Icon=$ICON
Path=$APP_ROOT
Terminal=false
Categories=Graphics;Development;
StartupNotify=true
EOF
chmod 0755 "$MENU_ENTRY"

cp "$MENU_ENTRY" "$DESKTOP_ENTRY"
chmod 0755 "$DESKTOP_ENTRY"

# GNOME shows "Untrusted application launcher" on the first double-click until
# the file is both executable and flagged; KDE and XFCE go by the mode alone.
if command -v gio >/dev/null; then
    gio set "$DESKTOP_ENTRY" metadata::trusted true 2>/dev/null || true
fi
# Nautilus only re-reads the flag when the mtime moves.
touch "$DESKTOP_ENTRY"

command -v update-desktop-database >/dev/null && \
    update-desktop-database "$MENU_DIR" 2>/dev/null || true

echo "launcher   : $LAUNCHER"
echo "desktop    : $DESKTOP_ENTRY"
echo "menu entry : $MENU_ENTRY"
echo "icon       : $ICON"

# -- 4. only now, start it ---------------------------------------------------
# exec, so ShotDeck replaces this shell: one process, and the exit status the
# artist sees is the app's own.
echo "starting ShotDeck"
exec "$LAUNCHER"
